# Generated by Django 5.1.3 on 2024-12-25 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quran", "0002_fatwa_order_subscribedusers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exchangedetail",
            name="number_cash_wallet",
            field=models.IntegerField(),
        ),
    ]
