# Generated by Django 5.1.3 on 2024-12-25 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quran", "0003_alter_exchangedetail_number_cash_wallet"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exchangedetail",
            old_name="number_cash_wallet",
            new_name="number",
        ),
    ]
