# Generated by Django 5.1.3 on 2024-12-11 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quran", "0003_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="fatwa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("answer", models.TextField()),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="order",
            name="name",
            field=models.CharField(default="", max_length=100),
        ),
    ]
