# Generated by Django 5.1.3 on 2024-12-13 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quran", "0004_fatwa_alter_order_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="fatwa",
            name="name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="article",
            name="article_slug",
            field=models.SlugField(unique=True, verbose_name="gategory slug"),
        ),
        migrations.AlterField(
            model_name="article",
            name="series",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="quran.articleseries",
                verbose_name="sheik",
            ),
        ),
        migrations.AlterField(
            model_name="articleseries",
            name="slug",
            field=models.SlugField(unique=True, verbose_name="Sheik slug"),
        ),
    ]
