# Generated by Django 5.1.3 on 2024-12-26 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quran", "0004_alter_exchangedetail_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exchangedetail",
            old_name="created_at",
            new_name="date_filled",
        ),
        migrations.RemoveField(
            model_name="exchangedetail",
            name="number_cash_wallet",
        ),
        migrations.AddField(
            model_name="exchangedetail",
            name="wall_number",
            field=models.CharField(default="", max_length=100),
        ),
    ]
