# Generated by Django 5.1.3 on 2024-12-26 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quran", "0005_rename_created_at_exchangedetail_date_filled_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ExchangeDetail",
        ),
    ]
