# Generated by Django 5.1.3 on 2024-12-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quran", "0006_exchangedetail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exchangedetail",
            name="screenshot",
            field=models.ImageField(upload_to="media/"),
        ),
    ]
