# Generated by Django 5.1.3 on 2024-12-26 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quran", "0006_delete_exchangedetail"),
    ]

    operations = [
        migrations.CreateModel(
            name="WallEntry_yearly",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wall_number", models.CharField(max_length=100)),
                ("screenshot", models.ImageField(upload_to="screenshots/yearly")),
                ("date_filled", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
