# Generated by Django 5.1.3 on 2024-12-26 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quran", "0007_wallentry_yearly"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="WallEntry",
            new_name="WallEntry_100",
        ),
        migrations.RenameModel(
            old_name="WallEntry_yearly",
            new_name="WallEntry_200",
        ),
    ]
