# Generated by Django 5.1.3 on 2024-12-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quran", "0008_rename_wallentry_wallentry_100_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="videos/"),
        ),
    ]
