# Generated by Django 5.1.3 on 2024-12-20 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quran", "0009_exchangedetail_accusername"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exchangedetail",
            name="accusername",
        ),
        migrations.AddField(
            model_name="exchangedetail",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="user_exchange_details",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
