# Generated by Django 5.1.3 on 2024-12-21 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quran", "0014_alter_order_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="email",
            field=models.EmailField(default="dha@gmail.com", max_length=100),
        ),
    ]
